---
collections:
  - name: community.general
    version: ">=11.0.0"
  - name: ansible.posix
    version: ">=2.0.0"
  - name: community.mysql
    version: ">=3.0.0"
  - name: community.postgresql
    version: ">=4.0.0"
